package com.zjzc.manage.core.model.po;

public class TblZcsysArbitrationPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.arbtr_code
     *
     * @mbggenerated
     */
    private String arbtrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.client_casecode
     *
     * @mbggenerated
     */
    private String clientCasecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.client_prod_type
     *
     * @mbggenerated
     */
    private String clientProdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.client_company_code
     *
     * @mbggenerated
     */
    private String clientCompanyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.client_company_subcode
     *
     * @mbggenerated
     */
    private String clientCompanySubcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.client_company_fullname
     *
     * @mbggenerated
     */
    private String clientCompanyFullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.client_company_address
     *
     * @mbggenerated
     */
    private String clientCompanyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.client_company_shortname
     *
     * @mbggenerated
     */
    private String clientCompanyShortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.trigger_arbtr_reason
     *
     * @mbggenerated
     */
    private String triggerArbtrReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.contract_amount
     *
     * @mbggenerated
     */
    private String contractAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_amount
     *
     * @mbggenerated
     */
    private String loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.batch_flag
     *
     * @mbggenerated
     */
    private String batchFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.contract_sign_ts
     *
     * @mbggenerated
     */
    private String contractSignTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_apply_ts
     *
     * @mbggenerated
     */
    private String loanApplyTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_start_ts
     *
     * @mbggenerated
     */
    private String loanStartTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_end_ts
     *
     * @mbggenerated
     */
    private String loanEndTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_period
     *
     * @mbggenerated
     */
    private String loanPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_period_unit
     *
     * @mbggenerated
     */
    private String loanPeriodUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_interest_yearly
     *
     * @mbggenerated
     */
    private String loanInterestYearly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_penal_interest_daily
     *
     * @mbggenerated
     */
    private String loanPenalInterestDaily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_mortgage
     *
     * @mbggenerated
     */
    private String loanMortgage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_usage
     *
     * @mbggenerated
     */
    private String loanUsage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_ppl_name
     *
     * @mbggenerated
     */
    private String loanPplName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_ppl_sex
     *
     * @mbggenerated
     */
    private String loanPplSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_ppl_nation
     *
     * @mbggenerated
     */
    private String loanPplNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_ppl_id
     *
     * @mbggenerated
     */
    private String loanPplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_ppl_address
     *
     * @mbggenerated
     */
    private String loanPplAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_ppl_phone
     *
     * @mbggenerated
     */
    private String loanPplPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_foreign_related
     *
     * @mbggenerated
     */
    private String loanForeignRelated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.backup_field1
     *
     * @mbggenerated
     */
    private String backupField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.backup_field2
     *
     * @mbggenerated
     */
    private String backupField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.backup_field3
     *
     * @mbggenerated
     */
    private String backupField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.attachment
     *
     * @mbggenerated
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.attachment_path1
     *
     * @mbggenerated
     */
    private String attachmentPath1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.attachment_path2
     *
     * @mbggenerated
     */
    private String attachmentPath2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.paid_for_arbtr
     *
     * @mbggenerated
     */
    private String paidForArbtr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.triggered_arbtr
     *
     * @mbggenerated
     */
    private String triggeredArbtr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.rcd_created_ts
     *
     * @mbggenerated
     */
    private String rcdCreatedTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.last_upd_dt
     *
     * @mbggenerated
     */
    private String lastUpdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.last_upd_usr
     *
     * @mbggenerated
     */
    private String lastUpdUsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.send_type
     *
     * @mbggenerated
     */
    private String sendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.email_address
     *
     * @mbggenerated
     */
    private String emailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.physical_address
     *
     * @mbggenerated
     */
    private String physicalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.package_name
     *
     * @mbggenerated
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_credit_code
     *
     * @mbggenerated
     */
    private String loanCreditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_company_type
     *
     * @mbggenerated
     */
    private String loanCompanyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_company_corporation
     *
     * @mbggenerated
     */
    private String loanCompanyCorporation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_company_phone_no
     *
     * @mbggenerated
     */
    private String loanCompanyPhoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_company_address
     *
     * @mbggenerated
     */
    private String loanCompanyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_company_name
     *
     * @mbggenerated
     */
    private String loanCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.upload_oss_time
     *
     * @mbggenerated
     */
    private String uploadOssTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.loan_is_company
     *
     * @mbggenerated
     */
    private String loanIsCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.off_line_time
     *
     * @mbggenerated
     */
    private String offLineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.del_casefile_time
     *
     * @mbggenerated
     */
    private String delCasefileTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zcsys_arbitration.records
     *
     * @mbggenerated
     */
    private String records;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.id
     *
     * @return the value of zcsys_arbitration.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.id
     *
     * @param id the value for zcsys_arbitration.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.arbtr_code
     *
     * @return the value of zcsys_arbitration.arbtr_code
     *
     * @mbggenerated
     */
    public String getArbtrCode() {
        return arbtrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.arbtr_code
     *
     * @param arbtrCode the value for zcsys_arbitration.arbtr_code
     *
     * @mbggenerated
     */
    public void setArbtrCode(String arbtrCode) {
        this.arbtrCode = arbtrCode == null ? null : arbtrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.client_casecode
     *
     * @return the value of zcsys_arbitration.client_casecode
     *
     * @mbggenerated
     */
    public String getClientCasecode() {
        return clientCasecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.client_casecode
     *
     * @param clientCasecode the value for zcsys_arbitration.client_casecode
     *
     * @mbggenerated
     */
    public void setClientCasecode(String clientCasecode) {
        this.clientCasecode = clientCasecode == null ? null : clientCasecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.client_prod_type
     *
     * @return the value of zcsys_arbitration.client_prod_type
     *
     * @mbggenerated
     */
    public String getClientProdType() {
        return clientProdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.client_prod_type
     *
     * @param clientProdType the value for zcsys_arbitration.client_prod_type
     *
     * @mbggenerated
     */
    public void setClientProdType(String clientProdType) {
        this.clientProdType = clientProdType == null ? null : clientProdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.client_company_code
     *
     * @return the value of zcsys_arbitration.client_company_code
     *
     * @mbggenerated
     */
    public String getClientCompanyCode() {
        return clientCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.client_company_code
     *
     * @param clientCompanyCode the value for zcsys_arbitration.client_company_code
     *
     * @mbggenerated
     */
    public void setClientCompanyCode(String clientCompanyCode) {
        this.clientCompanyCode = clientCompanyCode == null ? null : clientCompanyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.client_company_subcode
     *
     * @return the value of zcsys_arbitration.client_company_subcode
     *
     * @mbggenerated
     */
    public String getClientCompanySubcode() {
        return clientCompanySubcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.client_company_subcode
     *
     * @param clientCompanySubcode the value for zcsys_arbitration.client_company_subcode
     *
     * @mbggenerated
     */
    public void setClientCompanySubcode(String clientCompanySubcode) {
        this.clientCompanySubcode = clientCompanySubcode == null ? null : clientCompanySubcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.client_company_fullname
     *
     * @return the value of zcsys_arbitration.client_company_fullname
     *
     * @mbggenerated
     */
    public String getClientCompanyFullname() {
        return clientCompanyFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.client_company_fullname
     *
     * @param clientCompanyFullname the value for zcsys_arbitration.client_company_fullname
     *
     * @mbggenerated
     */
    public void setClientCompanyFullname(String clientCompanyFullname) {
        this.clientCompanyFullname = clientCompanyFullname == null ? null : clientCompanyFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.client_company_address
     *
     * @return the value of zcsys_arbitration.client_company_address
     *
     * @mbggenerated
     */
    public String getClientCompanyAddress() {
        return clientCompanyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.client_company_address
     *
     * @param clientCompanyAddress the value for zcsys_arbitration.client_company_address
     *
     * @mbggenerated
     */
    public void setClientCompanyAddress(String clientCompanyAddress) {
        this.clientCompanyAddress = clientCompanyAddress == null ? null : clientCompanyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.client_company_shortname
     *
     * @return the value of zcsys_arbitration.client_company_shortname
     *
     * @mbggenerated
     */
    public String getClientCompanyShortname() {
        return clientCompanyShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.client_company_shortname
     *
     * @param clientCompanyShortname the value for zcsys_arbitration.client_company_shortname
     *
     * @mbggenerated
     */
    public void setClientCompanyShortname(String clientCompanyShortname) {
        this.clientCompanyShortname = clientCompanyShortname == null ? null : clientCompanyShortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.trigger_arbtr_reason
     *
     * @return the value of zcsys_arbitration.trigger_arbtr_reason
     *
     * @mbggenerated
     */
    public String getTriggerArbtrReason() {
        return triggerArbtrReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.trigger_arbtr_reason
     *
     * @param triggerArbtrReason the value for zcsys_arbitration.trigger_arbtr_reason
     *
     * @mbggenerated
     */
    public void setTriggerArbtrReason(String triggerArbtrReason) {
        this.triggerArbtrReason = triggerArbtrReason == null ? null : triggerArbtrReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.contract_amount
     *
     * @return the value of zcsys_arbitration.contract_amount
     *
     * @mbggenerated
     */
    public String getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.contract_amount
     *
     * @param contractAmount the value for zcsys_arbitration.contract_amount
     *
     * @mbggenerated
     */
    public void setContractAmount(String contractAmount) {
        this.contractAmount = contractAmount == null ? null : contractAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_amount
     *
     * @return the value of zcsys_arbitration.loan_amount
     *
     * @mbggenerated
     */
    public String getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_amount
     *
     * @param loanAmount the value for zcsys_arbitration.loan_amount
     *
     * @mbggenerated
     */
    public void setLoanAmount(String loanAmount) {
        this.loanAmount = loanAmount == null ? null : loanAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.batch_flag
     *
     * @return the value of zcsys_arbitration.batch_flag
     *
     * @mbggenerated
     */
    public String getBatchFlag() {
        return batchFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.batch_flag
     *
     * @param batchFlag the value for zcsys_arbitration.batch_flag
     *
     * @mbggenerated
     */
    public void setBatchFlag(String batchFlag) {
        this.batchFlag = batchFlag == null ? null : batchFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.contract_sign_ts
     *
     * @return the value of zcsys_arbitration.contract_sign_ts
     *
     * @mbggenerated
     */
    public String getContractSignTs() {
        return contractSignTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.contract_sign_ts
     *
     * @param contractSignTs the value for zcsys_arbitration.contract_sign_ts
     *
     * @mbggenerated
     */
    public void setContractSignTs(String contractSignTs) {
        this.contractSignTs = contractSignTs == null ? null : contractSignTs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_apply_ts
     *
     * @return the value of zcsys_arbitration.loan_apply_ts
     *
     * @mbggenerated
     */
    public String getLoanApplyTs() {
        return loanApplyTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_apply_ts
     *
     * @param loanApplyTs the value for zcsys_arbitration.loan_apply_ts
     *
     * @mbggenerated
     */
    public void setLoanApplyTs(String loanApplyTs) {
        this.loanApplyTs = loanApplyTs == null ? null : loanApplyTs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_start_ts
     *
     * @return the value of zcsys_arbitration.loan_start_ts
     *
     * @mbggenerated
     */
    public String getLoanStartTs() {
        return loanStartTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_start_ts
     *
     * @param loanStartTs the value for zcsys_arbitration.loan_start_ts
     *
     * @mbggenerated
     */
    public void setLoanStartTs(String loanStartTs) {
        this.loanStartTs = loanStartTs == null ? null : loanStartTs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_end_ts
     *
     * @return the value of zcsys_arbitration.loan_end_ts
     *
     * @mbggenerated
     */
    public String getLoanEndTs() {
        return loanEndTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_end_ts
     *
     * @param loanEndTs the value for zcsys_arbitration.loan_end_ts
     *
     * @mbggenerated
     */
    public void setLoanEndTs(String loanEndTs) {
        this.loanEndTs = loanEndTs == null ? null : loanEndTs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_period
     *
     * @return the value of zcsys_arbitration.loan_period
     *
     * @mbggenerated
     */
    public String getLoanPeriod() {
        return loanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_period
     *
     * @param loanPeriod the value for zcsys_arbitration.loan_period
     *
     * @mbggenerated
     */
    public void setLoanPeriod(String loanPeriod) {
        this.loanPeriod = loanPeriod == null ? null : loanPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_period_unit
     *
     * @return the value of zcsys_arbitration.loan_period_unit
     *
     * @mbggenerated
     */
    public String getLoanPeriodUnit() {
        return loanPeriodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_period_unit
     *
     * @param loanPeriodUnit the value for zcsys_arbitration.loan_period_unit
     *
     * @mbggenerated
     */
    public void setLoanPeriodUnit(String loanPeriodUnit) {
        this.loanPeriodUnit = loanPeriodUnit == null ? null : loanPeriodUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_interest_yearly
     *
     * @return the value of zcsys_arbitration.loan_interest_yearly
     *
     * @mbggenerated
     */
    public String getLoanInterestYearly() {
        return loanInterestYearly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_interest_yearly
     *
     * @param loanInterestYearly the value for zcsys_arbitration.loan_interest_yearly
     *
     * @mbggenerated
     */
    public void setLoanInterestYearly(String loanInterestYearly) {
        this.loanInterestYearly = loanInterestYearly == null ? null : loanInterestYearly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_penal_interest_daily
     *
     * @return the value of zcsys_arbitration.loan_penal_interest_daily
     *
     * @mbggenerated
     */
    public String getLoanPenalInterestDaily() {
        return loanPenalInterestDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_penal_interest_daily
     *
     * @param loanPenalInterestDaily the value for zcsys_arbitration.loan_penal_interest_daily
     *
     * @mbggenerated
     */
    public void setLoanPenalInterestDaily(String loanPenalInterestDaily) {
        this.loanPenalInterestDaily = loanPenalInterestDaily == null ? null : loanPenalInterestDaily.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_mortgage
     *
     * @return the value of zcsys_arbitration.loan_mortgage
     *
     * @mbggenerated
     */
    public String getLoanMortgage() {
        return loanMortgage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_mortgage
     *
     * @param loanMortgage the value for zcsys_arbitration.loan_mortgage
     *
     * @mbggenerated
     */
    public void setLoanMortgage(String loanMortgage) {
        this.loanMortgage = loanMortgage == null ? null : loanMortgage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_usage
     *
     * @return the value of zcsys_arbitration.loan_usage
     *
     * @mbggenerated
     */
    public String getLoanUsage() {
        return loanUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_usage
     *
     * @param loanUsage the value for zcsys_arbitration.loan_usage
     *
     * @mbggenerated
     */
    public void setLoanUsage(String loanUsage) {
        this.loanUsage = loanUsage == null ? null : loanUsage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_ppl_name
     *
     * @return the value of zcsys_arbitration.loan_ppl_name
     *
     * @mbggenerated
     */
    public String getLoanPplName() {
        return loanPplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_ppl_name
     *
     * @param loanPplName the value for zcsys_arbitration.loan_ppl_name
     *
     * @mbggenerated
     */
    public void setLoanPplName(String loanPplName) {
        this.loanPplName = loanPplName == null ? null : loanPplName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_ppl_sex
     *
     * @return the value of zcsys_arbitration.loan_ppl_sex
     *
     * @mbggenerated
     */
    public String getLoanPplSex() {
        return loanPplSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_ppl_sex
     *
     * @param loanPplSex the value for zcsys_arbitration.loan_ppl_sex
     *
     * @mbggenerated
     */
    public void setLoanPplSex(String loanPplSex) {
        this.loanPplSex = loanPplSex == null ? null : loanPplSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_ppl_nation
     *
     * @return the value of zcsys_arbitration.loan_ppl_nation
     *
     * @mbggenerated
     */
    public String getLoanPplNation() {
        return loanPplNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_ppl_nation
     *
     * @param loanPplNation the value for zcsys_arbitration.loan_ppl_nation
     *
     * @mbggenerated
     */
    public void setLoanPplNation(String loanPplNation) {
        this.loanPplNation = loanPplNation == null ? null : loanPplNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_ppl_id
     *
     * @return the value of zcsys_arbitration.loan_ppl_id
     *
     * @mbggenerated
     */
    public String getLoanPplId() {
        return loanPplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_ppl_id
     *
     * @param loanPplId the value for zcsys_arbitration.loan_ppl_id
     *
     * @mbggenerated
     */
    public void setLoanPplId(String loanPplId) {
        this.loanPplId = loanPplId == null ? null : loanPplId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_ppl_address
     *
     * @return the value of zcsys_arbitration.loan_ppl_address
     *
     * @mbggenerated
     */
    public String getLoanPplAddress() {
        return loanPplAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_ppl_address
     *
     * @param loanPplAddress the value for zcsys_arbitration.loan_ppl_address
     *
     * @mbggenerated
     */
    public void setLoanPplAddress(String loanPplAddress) {
        this.loanPplAddress = loanPplAddress == null ? null : loanPplAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_ppl_phone
     *
     * @return the value of zcsys_arbitration.loan_ppl_phone
     *
     * @mbggenerated
     */
    public String getLoanPplPhone() {
        return loanPplPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_ppl_phone
     *
     * @param loanPplPhone the value for zcsys_arbitration.loan_ppl_phone
     *
     * @mbggenerated
     */
    public void setLoanPplPhone(String loanPplPhone) {
        this.loanPplPhone = loanPplPhone == null ? null : loanPplPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_foreign_related
     *
     * @return the value of zcsys_arbitration.loan_foreign_related
     *
     * @mbggenerated
     */
    public String getLoanForeignRelated() {
        return loanForeignRelated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_foreign_related
     *
     * @param loanForeignRelated the value for zcsys_arbitration.loan_foreign_related
     *
     * @mbggenerated
     */
    public void setLoanForeignRelated(String loanForeignRelated) {
        this.loanForeignRelated = loanForeignRelated == null ? null : loanForeignRelated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.backup_field1
     *
     * @return the value of zcsys_arbitration.backup_field1
     *
     * @mbggenerated
     */
    public String getBackupField1() {
        return backupField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.backup_field1
     *
     * @param backupField1 the value for zcsys_arbitration.backup_field1
     *
     * @mbggenerated
     */
    public void setBackupField1(String backupField1) {
        this.backupField1 = backupField1 == null ? null : backupField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.backup_field2
     *
     * @return the value of zcsys_arbitration.backup_field2
     *
     * @mbggenerated
     */
    public String getBackupField2() {
        return backupField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.backup_field2
     *
     * @param backupField2 the value for zcsys_arbitration.backup_field2
     *
     * @mbggenerated
     */
    public void setBackupField2(String backupField2) {
        this.backupField2 = backupField2 == null ? null : backupField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.backup_field3
     *
     * @return the value of zcsys_arbitration.backup_field3
     *
     * @mbggenerated
     */
    public String getBackupField3() {
        return backupField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.backup_field3
     *
     * @param backupField3 the value for zcsys_arbitration.backup_field3
     *
     * @mbggenerated
     */
    public void setBackupField3(String backupField3) {
        this.backupField3 = backupField3 == null ? null : backupField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.attachment
     *
     * @return the value of zcsys_arbitration.attachment
     *
     * @mbggenerated
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.attachment
     *
     * @param attachment the value for zcsys_arbitration.attachment
     *
     * @mbggenerated
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.attachment_path1
     *
     * @return the value of zcsys_arbitration.attachment_path1
     *
     * @mbggenerated
     */
    public String getAttachmentPath1() {
        return attachmentPath1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.attachment_path1
     *
     * @param attachmentPath1 the value for zcsys_arbitration.attachment_path1
     *
     * @mbggenerated
     */
    public void setAttachmentPath1(String attachmentPath1) {
        this.attachmentPath1 = attachmentPath1 == null ? null : attachmentPath1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.attachment_path2
     *
     * @return the value of zcsys_arbitration.attachment_path2
     *
     * @mbggenerated
     */
    public String getAttachmentPath2() {
        return attachmentPath2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.attachment_path2
     *
     * @param attachmentPath2 the value for zcsys_arbitration.attachment_path2
     *
     * @mbggenerated
     */
    public void setAttachmentPath2(String attachmentPath2) {
        this.attachmentPath2 = attachmentPath2 == null ? null : attachmentPath2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.paid_for_arbtr
     *
     * @return the value of zcsys_arbitration.paid_for_arbtr
     *
     * @mbggenerated
     */
    public String getPaidForArbtr() {
        return paidForArbtr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.paid_for_arbtr
     *
     * @param paidForArbtr the value for zcsys_arbitration.paid_for_arbtr
     *
     * @mbggenerated
     */
    public void setPaidForArbtr(String paidForArbtr) {
        this.paidForArbtr = paidForArbtr == null ? null : paidForArbtr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.triggered_arbtr
     *
     * @return the value of zcsys_arbitration.triggered_arbtr
     *
     * @mbggenerated
     */
    public String getTriggeredArbtr() {
        return triggeredArbtr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.triggered_arbtr
     *
     * @param triggeredArbtr the value for zcsys_arbitration.triggered_arbtr
     *
     * @mbggenerated
     */
    public void setTriggeredArbtr(String triggeredArbtr) {
        this.triggeredArbtr = triggeredArbtr == null ? null : triggeredArbtr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.rcd_created_ts
     *
     * @return the value of zcsys_arbitration.rcd_created_ts
     *
     * @mbggenerated
     */
    public String getRcdCreatedTs() {
        return rcdCreatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.rcd_created_ts
     *
     * @param rcdCreatedTs the value for zcsys_arbitration.rcd_created_ts
     *
     * @mbggenerated
     */
    public void setRcdCreatedTs(String rcdCreatedTs) {
        this.rcdCreatedTs = rcdCreatedTs == null ? null : rcdCreatedTs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.last_upd_dt
     *
     * @return the value of zcsys_arbitration.last_upd_dt
     *
     * @mbggenerated
     */
    public String getLastUpdDt() {
        return lastUpdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.last_upd_dt
     *
     * @param lastUpdDt the value for zcsys_arbitration.last_upd_dt
     *
     * @mbggenerated
     */
    public void setLastUpdDt(String lastUpdDt) {
        this.lastUpdDt = lastUpdDt == null ? null : lastUpdDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.last_upd_usr
     *
     * @return the value of zcsys_arbitration.last_upd_usr
     *
     * @mbggenerated
     */
    public String getLastUpdUsr() {
        return lastUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.last_upd_usr
     *
     * @param lastUpdUsr the value for zcsys_arbitration.last_upd_usr
     *
     * @mbggenerated
     */
    public void setLastUpdUsr(String lastUpdUsr) {
        this.lastUpdUsr = lastUpdUsr == null ? null : lastUpdUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.send_type
     *
     * @return the value of zcsys_arbitration.send_type
     *
     * @mbggenerated
     */
    public String getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.send_type
     *
     * @param sendType the value for zcsys_arbitration.send_type
     *
     * @mbggenerated
     */
    public void setSendType(String sendType) {
        this.sendType = sendType == null ? null : sendType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.email_address
     *
     * @return the value of zcsys_arbitration.email_address
     *
     * @mbggenerated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.email_address
     *
     * @param emailAddress the value for zcsys_arbitration.email_address
     *
     * @mbggenerated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.physical_address
     *
     * @return the value of zcsys_arbitration.physical_address
     *
     * @mbggenerated
     */
    public String getPhysicalAddress() {
        return physicalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.physical_address
     *
     * @param physicalAddress the value for zcsys_arbitration.physical_address
     *
     * @mbggenerated
     */
    public void setPhysicalAddress(String physicalAddress) {
        this.physicalAddress = physicalAddress == null ? null : physicalAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.package_name
     *
     * @return the value of zcsys_arbitration.package_name
     *
     * @mbggenerated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.package_name
     *
     * @param packageName the value for zcsys_arbitration.package_name
     *
     * @mbggenerated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_credit_code
     *
     * @return the value of zcsys_arbitration.loan_credit_code
     *
     * @mbggenerated
     */
    public String getLoanCreditCode() {
        return loanCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_credit_code
     *
     * @param loanCreditCode the value for zcsys_arbitration.loan_credit_code
     *
     * @mbggenerated
     */
    public void setLoanCreditCode(String loanCreditCode) {
        this.loanCreditCode = loanCreditCode == null ? null : loanCreditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_company_type
     *
     * @return the value of zcsys_arbitration.loan_company_type
     *
     * @mbggenerated
     */
    public String getLoanCompanyType() {
        return loanCompanyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_company_type
     *
     * @param loanCompanyType the value for zcsys_arbitration.loan_company_type
     *
     * @mbggenerated
     */
    public void setLoanCompanyType(String loanCompanyType) {
        this.loanCompanyType = loanCompanyType == null ? null : loanCompanyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_company_corporation
     *
     * @return the value of zcsys_arbitration.loan_company_corporation
     *
     * @mbggenerated
     */
    public String getLoanCompanyCorporation() {
        return loanCompanyCorporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_company_corporation
     *
     * @param loanCompanyCorporation the value for zcsys_arbitration.loan_company_corporation
     *
     * @mbggenerated
     */
    public void setLoanCompanyCorporation(String loanCompanyCorporation) {
        this.loanCompanyCorporation = loanCompanyCorporation == null ? null : loanCompanyCorporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_company_phone_no
     *
     * @return the value of zcsys_arbitration.loan_company_phone_no
     *
     * @mbggenerated
     */
    public String getLoanCompanyPhoneNo() {
        return loanCompanyPhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_company_phone_no
     *
     * @param loanCompanyPhoneNo the value for zcsys_arbitration.loan_company_phone_no
     *
     * @mbggenerated
     */
    public void setLoanCompanyPhoneNo(String loanCompanyPhoneNo) {
        this.loanCompanyPhoneNo = loanCompanyPhoneNo == null ? null : loanCompanyPhoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_company_address
     *
     * @return the value of zcsys_arbitration.loan_company_address
     *
     * @mbggenerated
     */
    public String getLoanCompanyAddress() {
        return loanCompanyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_company_address
     *
     * @param loanCompanyAddress the value for zcsys_arbitration.loan_company_address
     *
     * @mbggenerated
     */
    public void setLoanCompanyAddress(String loanCompanyAddress) {
        this.loanCompanyAddress = loanCompanyAddress == null ? null : loanCompanyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_company_name
     *
     * @return the value of zcsys_arbitration.loan_company_name
     *
     * @mbggenerated
     */
    public String getLoanCompanyName() {
        return loanCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_company_name
     *
     * @param loanCompanyName the value for zcsys_arbitration.loan_company_name
     *
     * @mbggenerated
     */
    public void setLoanCompanyName(String loanCompanyName) {
        this.loanCompanyName = loanCompanyName == null ? null : loanCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.upload_oss_time
     *
     * @return the value of zcsys_arbitration.upload_oss_time
     *
     * @mbggenerated
     */
    public String getUploadOssTime() {
        return uploadOssTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.upload_oss_time
     *
     * @param uploadOssTime the value for zcsys_arbitration.upload_oss_time
     *
     * @mbggenerated
     */
    public void setUploadOssTime(String uploadOssTime) {
        this.uploadOssTime = uploadOssTime == null ? null : uploadOssTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.loan_is_company
     *
     * @return the value of zcsys_arbitration.loan_is_company
     *
     * @mbggenerated
     */
    public String getLoanIsCompany() {
        return loanIsCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.loan_is_company
     *
     * @param loanIsCompany the value for zcsys_arbitration.loan_is_company
     *
     * @mbggenerated
     */
    public void setLoanIsCompany(String loanIsCompany) {
        this.loanIsCompany = loanIsCompany == null ? null : loanIsCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.off_line_time
     *
     * @return the value of zcsys_arbitration.off_line_time
     *
     * @mbggenerated
     */
    public String getOffLineTime() {
        return offLineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.off_line_time
     *
     * @param offLineTime the value for zcsys_arbitration.off_line_time
     *
     * @mbggenerated
     */
    public void setOffLineTime(String offLineTime) {
        this.offLineTime = offLineTime == null ? null : offLineTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.del_casefile_time
     *
     * @return the value of zcsys_arbitration.del_casefile_time
     *
     * @mbggenerated
     */
    public String getDelCasefileTime() {
        return delCasefileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.del_casefile_time
     *
     * @param delCasefileTime the value for zcsys_arbitration.del_casefile_time
     *
     * @mbggenerated
     */
    public void setDelCasefileTime(String delCasefileTime) {
        this.delCasefileTime = delCasefileTime == null ? null : delCasefileTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zcsys_arbitration.records
     *
     * @return the value of zcsys_arbitration.records
     *
     * @mbggenerated
     */
    public String getRecords() {
        return records;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zcsys_arbitration.records
     *
     * @param records the value for zcsys_arbitration.records
     *
     * @mbggenerated
     */
    public void setRecords(String records) {
        this.records = records == null ? null : records.trim();
    }
}